import ProductView from '@/components/ProductView';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Barcha Mahsulotlar",
  description: "Generated by create next app",
};

const Product = async () => {
    const response = await fetch("https://dummyjson.com/products", {next:{revalidate: 60}}) // ISR
    const data = await response.json()
    
  return (
    <div>Product page
        <ProductView products={data?.products}/>
    </div>
  )
}

export default Product