import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Blog Qovunlar",
  description: "Generated by create next app",
};

const Blog = () => {
  // const token = localStorage.getItem("token")

  return (
    <div>Blog page</div>
  )
}

export default Blog