"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Metadata } from "next";
import { memo } from "react";

// export const metadata: Metadata = {
//   title: "About Qovun",
//   description: "Generated by create next app",
// };

const About = () => {
  const client = useQueryClient()
  // CSR
  const {data} = useQuery({
    queryKey: ["commentKey"],
    queryFn: () => fetch("https://68ca8602430c4476c349d48a.mockapi.io/comment").then(res => res.json()),
    enabled: true, // true
    retry: 3, // 3
    refetchOnWindowFocus: false, // true
    staleTime: 1000 * 60, // 0
    gcTime: 1000 * 60 * 10 // 10 min
  })

  // yozasiz -> yod -> tushunish
  
  const createMutation = useMutation<any, any, any>({
    mutationFn: (body) => fetch("https://68ca8602430c4476c349d48a.mockapi.io/comment", {
      method: "POST",
      headers: {"Content-Type" : "application/json"},
      body: JSON.stringify(body)
    }),
    onSuccess:()=>{
      client.invalidateQueries({queryKey: ["commentKey"]})
    }
  })

  //  const {data} = useQuery({
  //   queryKey: ["categoryKey"],
  //   queryFn: () => fetch("category").then(res => res.json()),
  //   enabled: true, // true
  //   retry: 3, // 3
  //   refetchOnWindowFocus: false, // true
  //   staleTime: 1000 * 60 * 5, // 0
  //   gcTime: 1000 * 60 * 10 // 10 min
  // })

  //  const {data} = useQuery({
  //   queryKey: ["productKey"],
  //   queryFn: () => fetch("product").then(res => res.json()),
  //   enabled: true, // true
  //   retry: 3, // 3
  //   refetchOnWindowFocus: false, // true
  //   staleTime: 1000 * 60, // 0
  //   gcTime: 1000 * 60 * 10 // 10 min
  // })

  const handleCreateComment = () => {
    createMutation.mutate({text: "salom"})
  }

  return (
    <div>
      <h2>About Page</h2>
      <button onClick={handleCreateComment}>Create comment</button>
      {data?.map((item: any) => (
        <div key={item.id}>{item.text}</div>
      ))}
    </div>
  );
};

export default memo(About);
