import { Metadata } from 'next';
import { memo } from 'react';

export const metadata: Metadata = {
  title: "Contact us",
  description: "Generated by create next app",
};

const Contact = () => {
  return (
    <div>
      <h2>Contact Page</h2>
    </div>
  );
};

export default memo(Contact);